### ISSUE TITLE
Feature Request: Support for client-side methods

### ISSUE THREAD

**Issue by EliJDonahue** [ArasLabs/find-active-debuggers#1]
Project currently only searches C# and VB methods for debuggers. Should implement a search for Javascript methods as well.

**Comment by mptap** [comment]
@EliJDonahue: Does this look good? https://github.com/ArasLabs/find-active-debuggers/pull/2

**Comment by EliJDonahue** [comment]
Thanks for the pull request. I've merged it and will close out this issue.
