### ISSUE TITLE
Multi-line JavaScript comment may throw false positive

### ISSUE THREAD

**Issue by EliJDonahue** [ArasLabs/find-active-debuggers#3]
A debugger statement in a multiline JavaScript comment may throw a false positive. 

Ex:

```(JavaScript)
/* 
  test

  debugger;

*/
```

The Regex that is used for checking JavaScript methods needs to be updated to let this type of comment pass the test.

**Comment by cgillis-aras** [comment]
Fixed by ccf7d7ff22ad6075fb31ba83aa9c8d973f38a1f5
